import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from 'next/image'
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased animated-gradient`}
      >
        <div className="max-w-[920px] m-auto">
              <nav className="mb-2 mt-2 flex flex-row justify-between">
                <nav>
                  <Link href={"/"}>
                    <Image src="/globe.svg"
                      width={50}
                      height={50} 
                      alt='asdasd'
                    />
                  </Link>
                </nav>
                <nav className='flex flex-row items-center'>
                  <div className="flex flex-row">
                    <p className='mx-4'>text1</p>
                    <p className='mx-4'>text2</p>
                    <p className='mx-4'>text3</p>
                  </div>
                </nav>
              </nav>
            {children}
          <footer>

          </footer>
        </div>
      </body>
    </html>
  );
}
